[workspace]
members = [
        "doc/calculator",
        "doc/pascal/lalrpop",
        "doc/whitespace",
        "lalrpop-test",
        "lalrpop-util",
        "lalrpop",
]

[workspace.package]
repository = "https://github.com/lalrpop/lalrpop"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
license = "Apache-2.0 OR MIT"
version = "0.19.9" # LALRPOP
edition = "2021"
