[package]
name = "nobol"
version = "0.1.0"
edition = "2021"
authors = ["Felix S Klock II <pnkfelix@pnkfx.org>"]
build = "build.rs" # <-- We added this and everything after!
workspace = "../.."

[build-dependencies]
lalrpop = { version = "0.20.0", path = "../../lalrpop" }

[dependencies]
lalrpop-util = { version = "0.20.0", path = "../../lalrpop-util", features = ["lexer", "unicode"] }
