[lalrpop]
title = "LALRPOP Documentation"
description = "LALRPOP Documentation"
authors = ["LALRPOP Developers"]

[output.html]
mathjax-support = true
site-url = "/lalrpop/"

[output.html.playpen]
editable = true

[output.linkcheck]
