[package]
name = "lalrpop-test"
build = "build.rs"
workspace = ".."

repository.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
diff = "0.1.12"
regex = "1"

[dependencies.lalrpop-util]
path = "../lalrpop-util"

[build-dependencies.lalrpop]
path = "../lalrpop"
features = ["lexer"]

[features]
default = ["test-set"]
test-set = []
