name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt
      - name: Run tests
        run: |
          export RUST_BACKTRACE=1
          export CARGO_INCREMENTAL=0
          cargo build -p lalrpop
          cargo test --all --all-features
          # Check the documentation examples separately so that the `lexer` feature
          # specified in tests do not leak into them
          cargo check -p calculator
          cargo check -p pascal
          cargo check -p whitespace
